### ISSUE TITLE
Issue template, commit template, PR template 등록

### ISSUE THREAD

**Issue by seo2im** [ReactPiscine/ReactPiscine#1]
## Description
기본적인 github환경 구성

## TODO
- [ ] issue template 등록
- [ ] PR template 등록
- [ ] commit template 파일 업데이트
